"""add_phase_5_recovery_outcomes

Revision ID: 8c0ebfc92862
Revises: fbc0441235c0
Create Date: 2026-08-30 08:42:19.472227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c0ebfc92862'
down_revision: Union[str, Sequence[str], None] = 'fbc0441235c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recovery_outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('payment_id', sa.String(), nullable=True),
    sa.Column('checkout_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('recovered_amount', sa.Integer(), nullable=False),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('payment_link', sa.String(), nullable=True),
    sa.Column('message_status', sa.String(), nullable=True),
    sa.Column('outcome_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_outcomes_action'), 'recovery_outcomes', ['action'], unique=False)
    op.create_index(op.f('ix_recovery_outcomes_case_id'), 'recovery_outcomes', ['case_id'], unique=False)
    op.create_index(op.f('ix_recovery_outcomes_checkout_id'), 'recovery_outcomes', ['checkout_id'], unique=False)
    op.create_index(op.f('ix_recovery_outcomes_id'), 'recovery_outcomes', ['id'], unique=False)
    op.create_index(op.f('ix_recovery_outcomes_merchant_id'), 'recovery_outcomes', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_recovery_outcomes_payment_id'), 'recovery_outcomes', ['payment_id'], unique=False)
    op.create_index(op.f('ix_recovery_outcomes_status'), 'recovery_outcomes', ['status'], unique=False)
    op.drop_constraint(op.f('circuit_breaker_states_provider_key'), 'circuit_breaker_states', type_='unique')
    op.create_index(op.f('ix_circuit_breaker_states_id'), 'circuit_breaker_states', ['id'], unique=False)
    op.create_index(op.f('ix_circuit_breaker_states_provider'), 'circuit_breaker_states', ['provider'], unique=True)
    op.create_index(op.f('ix_recovery_action_logs_action'), 'recovery_action_logs', ['action'], unique=False)
    op.create_index(op.f('ix_recovery_action_logs_case_id'), 'recovery_action_logs', ['case_id'], unique=False)
    op.create_index(op.f('ix_recovery_action_logs_created_at'), 'recovery_action_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_recovery_action_logs_customer_id'), 'recovery_action_logs', ['customer_id'], unique=False)
    op.create_index(op.f('ix_recovery_action_logs_id'), 'recovery_action_logs', ['id'], unique=False)
    op.create_index(op.f('ix_recovery_action_logs_merchant_id'), 'recovery_action_logs', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_recovery_action_logs_status'), 'recovery_action_logs', ['status'], unique=False)
    op.create_index(op.f('ix_recovery_budgets_budget_date'), 'recovery_budgets', ['budget_date'], unique=False)
    op.create_index(op.f('ix_recovery_budgets_id'), 'recovery_budgets', ['id'], unique=False)
    op.create_index(op.f('ix_recovery_budgets_merchant_id'), 'recovery_budgets', ['merchant_id'], unique=False)
    op.drop_index(op.f('ix_recovery_cases_status'), table_name='recovery_cases')
    op.create_index(op.f('ix_recovery_cases_incident_provider'), 'recovery_cases', ['incident_provider'], unique=False)
    op.create_index(op.f('ix_recovery_cases_incident_type'), 'recovery_cases', ['incident_type'], unique=False)
    op.drop_column('recovery_cases', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recovery_cases', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_recovery_cases_incident_type'), table_name='recovery_cases')
    op.drop_index(op.f('ix_recovery_cases_incident_provider'), table_name='recovery_cases')
    op.create_index(op.f('ix_recovery_cases_status'), 'recovery_cases', ['status'], unique=False)
    op.drop_index(op.f('ix_recovery_budgets_merchant_id'), table_name='recovery_budgets')
    op.drop_index(op.f('ix_recovery_budgets_id'), table_name='recovery_budgets')
    op.drop_index(op.f('ix_recovery_budgets_budget_date'), table_name='recovery_budgets')
    op.drop_index(op.f('ix_recovery_action_logs_status'), table_name='recovery_action_logs')
    op.drop_index(op.f('ix_recovery_action_logs_merchant_id'), table_name='recovery_action_logs')
    op.drop_index(op.f('ix_recovery_action_logs_id'), table_name='recovery_action_logs')
    op.drop_index(op.f('ix_recovery_action_logs_customer_id'), table_name='recovery_action_logs')
    op.drop_index(op.f('ix_recovery_action_logs_created_at'), table_name='recovery_action_logs')
    op.drop_index(op.f('ix_recovery_action_logs_case_id'), table_name='recovery_action_logs')
    op.drop_index(op.f('ix_recovery_action_logs_action'), table_name='recovery_action_logs')
    op.drop_index(op.f('ix_circuit_breaker_states_provider'), table_name='circuit_breaker_states')
    op.drop_index(op.f('ix_circuit_breaker_states_id'), table_name='circuit_breaker_states')
    op.create_unique_constraint(op.f('circuit_breaker_states_provider_key'), 'circuit_breaker_states', ['provider'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_recovery_outcomes_status'), table_name='recovery_outcomes')
    op.drop_index(op.f('ix_recovery_outcomes_payment_id'), table_name='recovery_outcomes')
    op.drop_index(op.f('ix_recovery_outcomes_merchant_id'), table_name='recovery_outcomes')
    op.drop_index(op.f('ix_recovery_outcomes_id'), table_name='recovery_outcomes')
    op.drop_index(op.f('ix_recovery_outcomes_checkout_id'), table_name='recovery_outcomes')
    op.drop_index(op.f('ix_recovery_outcomes_case_id'), table_name='recovery_outcomes')
    op.drop_index(op.f('ix_recovery_outcomes_action'), table_name='recovery_outcomes')
    op.drop_table('recovery_outcomes')
    # ### end Alembic commands ###
