"""initial schema

Revision ID: c5d2c5fc1692
Revises: 
Create Date: 2026-09-02 01:44:49.547202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5d2c5fc1692'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkout_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('session_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checkout_sessions_customer_id'), 'checkout_sessions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_checkout_sessions_id'), 'checkout_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_checkout_sessions_merchant_id'), 'checkout_sessions', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_checkout_sessions_session_id'), 'checkout_sessions', ['session_id'], unique=True)
    op.create_index(op.f('ix_checkout_sessions_status'), 'checkout_sessions', ['status'], unique=False)
    op.create_table('circuit_breaker_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('failure_threshold', sa.Integer(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cooldown_seconds', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_circuit_breaker_states_id'), 'circuit_breaker_states', ['id'], unique=False)
    op.create_index(op.f('ix_circuit_breaker_states_provider'), 'circuit_breaker_states', ['provider'], unique=True)
    op.create_table('payment_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payment_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_events_event_id'), 'payment_events', ['event_id'], unique=True)
    op.create_index(op.f('ix_payment_events_event_type'), 'payment_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_payment_events_id'), 'payment_events', ['id'], unique=False)
    op.create_index(op.f('ix_payment_events_merchant_id'), 'payment_events', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_payment_events_payment_id'), 'payment_events', ['payment_id'], unique=False)
    op.create_index(op.f('ix_payment_events_status'), 'payment_events', ['status'], unique=False)
    op.create_table('recovery_action_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('block_reason', sa.String(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('latency_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_action_logs_action'), 'recovery_action_logs', ['action'], unique=False)
    op.create_index(op.f('ix_recovery_action_logs_case_id'), 'recovery_action_logs', ['case_id'], unique=False)
    op.create_index(op.f('ix_recovery_action_logs_created_at'), 'recovery_action_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_recovery_action_logs_customer_id'), 'recovery_action_logs', ['customer_id'], unique=False)
    op.create_index(op.f('ix_recovery_action_logs_id'), 'recovery_action_logs', ['id'], unique=False)
    op.create_index(op.f('ix_recovery_action_logs_merchant_id'), 'recovery_action_logs', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_recovery_action_logs_status'), 'recovery_action_logs', ['status'], unique=False)
    op.create_table('recovery_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('event_source', sa.String(), nullable=False),
    sa.Column('decision', sa.String(), nullable=True),
    sa.Column('reasoning', sa.String(), nullable=True),
    sa.Column('guardrail_result', sa.JSON(), nullable=True),
    sa.Column('execution_result', sa.JSON(), nullable=True),
    sa.Column('audit_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_audit_logs_case_id'), 'recovery_audit_logs', ['case_id'], unique=False)
    op.create_index(op.f('ix_recovery_audit_logs_created_at'), 'recovery_audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_recovery_audit_logs_event_type'), 'recovery_audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_recovery_audit_logs_id'), 'recovery_audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_recovery_audit_logs_merchant_id'), 'recovery_audit_logs', ['merchant_id'], unique=False)
    op.create_table('recovery_budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('budget_date', sa.Date(), nullable=False),
    sa.Column('daily_limit', sa.Float(), nullable=False),
    sa.Column('spent', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_budgets_budget_date'), 'recovery_budgets', ['budget_date'], unique=False)
    op.create_index(op.f('ix_recovery_budgets_id'), 'recovery_budgets', ['id'], unique=False)
    op.create_index(op.f('ix_recovery_budgets_merchant_id'), 'recovery_budgets', ['merchant_id'], unique=False)
    op.create_table('recovery_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=True),
    sa.Column('payment_id', sa.String(), nullable=True),
    sa.Column('checkout_id', sa.String(), nullable=True),
    sa.Column('case_type', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('revenue_at_risk', sa.Integer(), nullable=False),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('classification', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('classification_reason', sa.String(), nullable=True),
    sa.Column('incident_type', sa.String(), nullable=True),
    sa.Column('incident_provider', sa.String(), nullable=True),
    sa.Column('incident_detected', sa.Boolean(), nullable=False),
    sa.Column('routing', sa.String(), nullable=False),
    sa.Column('recommended_action', sa.String(), nullable=False),
    sa.Column('opportunity_score', sa.Float(), nullable=True),
    sa.Column('recovery_probability', sa.Float(), nullable=True),
    sa.Column('expected_recovery_value', sa.Float(), nullable=True),
    sa.Column('ai_diagnosis', sa.String(), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('action_reason', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('intelligence_status', sa.String(), nullable=False),
    sa.Column('customer_consent', sa.Boolean(), nullable=True),
    sa.Column('recovered', sa.Boolean(), nullable=False),
    sa.Column('recovered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('execution_status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('recovery_status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_cases_case_id'), 'recovery_cases', ['case_id'], unique=True)
    op.create_index(op.f('ix_recovery_cases_case_type'), 'recovery_cases', ['case_type'], unique=False)
    op.create_index(op.f('ix_recovery_cases_checkout_id'), 'recovery_cases', ['checkout_id'], unique=False)
    op.create_index(op.f('ix_recovery_cases_classification'), 'recovery_cases', ['classification'], unique=False)
    op.create_index(op.f('ix_recovery_cases_customer_id'), 'recovery_cases', ['customer_id'], unique=False)
    op.create_index(op.f('ix_recovery_cases_execution_status'), 'recovery_cases', ['execution_status'], unique=False)
    op.create_index(op.f('ix_recovery_cases_failure_reason'), 'recovery_cases', ['failure_reason'], unique=False)
    op.create_index(op.f('ix_recovery_cases_id'), 'recovery_cases', ['id'], unique=False)
    op.create_index(op.f('ix_recovery_cases_incident_provider'), 'recovery_cases', ['incident_provider'], unique=False)
    op.create_index(op.f('ix_recovery_cases_incident_type'), 'recovery_cases', ['incident_type'], unique=False)
    op.create_index(op.f('ix_recovery_cases_intelligence_status'), 'recovery_cases', ['intelligence_status'], unique=False)
    op.create_index(op.f('ix_recovery_cases_merchant_id'), 'recovery_cases', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_recovery_cases_opportunity_score'), 'recovery_cases', ['opportunity_score'], unique=False)
    op.create_index(op.f('ix_recovery_cases_payment_id'), 'recovery_cases', ['payment_id'], unique=False)
    op.create_index(op.f('ix_recovery_cases_priority'), 'recovery_cases', ['priority'], unique=False)
    op.create_index(op.f('ix_recovery_cases_recovered'), 'recovery_cases', ['recovered'], unique=False)
    op.create_index(op.f('ix_recovery_cases_recovery_status'), 'recovery_cases', ['recovery_status'], unique=False)
    op.create_index(op.f('ix_recovery_cases_routing'), 'recovery_cases', ['routing'], unique=False)
    op.create_table('recovery_outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('payment_id', sa.String(), nullable=True),
    sa.Column('checkout_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('recovered_amount', sa.Integer(), nullable=False),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('payment_link', sa.String(), nullable=True),
    sa.Column('message_status', sa.String(), nullable=True),
    sa.Column('outcome_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_outcomes_action'), 'recovery_outcomes', ['action'], unique=False)
    op.create_index(op.f('ix_recovery_outcomes_case_id'), 'recovery_outcomes', ['case_id'], unique=False)
    op.create_index(op.f('ix_recovery_outcomes_checkout_id'), 'recovery_outcomes', ['checkout_id'], unique=False)
    op.create_index(op.f('ix_recovery_outcomes_id'), 'recovery_outcomes', ['id'], unique=False)
    op.create_index(op.f('ix_recovery_outcomes_merchant_id'), 'recovery_outcomes', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_recovery_outcomes_payment_id'), 'recovery_outcomes', ['payment_id'], unique=False)
    op.create_index(op.f('ix_recovery_outcomes_status'), 'recovery_outcomes', ['status'], unique=False)
    op.create_table('recovery_postmortems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('failure_stage', sa.String(), nullable=False),
    sa.Column('attempted_action', sa.String(), nullable=True),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('root_cause', sa.String(), nullable=True),
    sa.Column('ai_diagnosis', sa.String(), nullable=True),
    sa.Column('guardrail_result', sa.JSON(), nullable=True),
    sa.Column('execution_result', sa.JSON(), nullable=True),
    sa.Column('recovery_status', sa.String(), nullable=False),
    sa.Column('recovered_amount', sa.Integer(), nullable=False),
    sa.Column('recommended_followup', sa.String(), nullable=True),
    sa.Column('postmortem_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_postmortems_attempted_action'), 'recovery_postmortems', ['attempted_action'], unique=False)
    op.create_index(op.f('ix_recovery_postmortems_case_id'), 'recovery_postmortems', ['case_id'], unique=False)
    op.create_index(op.f('ix_recovery_postmortems_created_at'), 'recovery_postmortems', ['created_at'], unique=False)
    op.create_index(op.f('ix_recovery_postmortems_failure_stage'), 'recovery_postmortems', ['failure_stage'], unique=False)
    op.create_index(op.f('ix_recovery_postmortems_id'), 'recovery_postmortems', ['id'], unique=False)
    op.create_index(op.f('ix_recovery_postmortems_merchant_id'), 'recovery_postmortems', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_recovery_postmortems_recovery_status'), 'recovery_postmortems', ['recovery_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recovery_postmortems_recovery_status'), table_name='recovery_postmortems')
    op.drop_index(op.f('ix_recovery_postmortems_merchant_id'), table_name='recovery_postmortems')
    op.drop_index(op.f('ix_recovery_postmortems_id'), table_name='recovery_postmortems')
    op.drop_index(op.f('ix_recovery_postmortems_failure_stage'), table_name='recovery_postmortems')
    op.drop_index(op.f('ix_recovery_postmortems_created_at'), table_name='recovery_postmortems')
    op.drop_index(op.f('ix_recovery_postmortems_case_id'), table_name='recovery_postmortems')
    op.drop_index(op.f('ix_recovery_postmortems_attempted_action'), table_name='recovery_postmortems')
    op.drop_table('recovery_postmortems')
    op.drop_index(op.f('ix_recovery_outcomes_status'), table_name='recovery_outcomes')
    op.drop_index(op.f('ix_recovery_outcomes_payment_id'), table_name='recovery_outcomes')
    op.drop_index(op.f('ix_recovery_outcomes_merchant_id'), table_name='recovery_outcomes')
    op.drop_index(op.f('ix_recovery_outcomes_id'), table_name='recovery_outcomes')
    op.drop_index(op.f('ix_recovery_outcomes_checkout_id'), table_name='recovery_outcomes')
    op.drop_index(op.f('ix_recovery_outcomes_case_id'), table_name='recovery_outcomes')
    op.drop_index(op.f('ix_recovery_outcomes_action'), table_name='recovery_outcomes')
    op.drop_table('recovery_outcomes')
    op.drop_index(op.f('ix_recovery_cases_routing'), table_name='recovery_cases')
    op.drop_index(op.f('ix_recovery_cases_recovery_status'), table_name='recovery_cases')
    op.drop_index(op.f('ix_recovery_cases_recovered'), table_name='recovery_cases')
    op.drop_index(op.f('ix_recovery_cases_priority'), table_name='recovery_cases')
    op.drop_index(op.f('ix_recovery_cases_payment_id'), table_name='recovery_cases')
    op.drop_index(op.f('ix_recovery_cases_opportunity_score'), table_name='recovery_cases')
    op.drop_index(op.f('ix_recovery_cases_merchant_id'), table_name='recovery_cases')
    op.drop_index(op.f('ix_recovery_cases_intelligence_status'), table_name='recovery_cases')
    op.drop_index(op.f('ix_recovery_cases_incident_type'), table_name='recovery_cases')
    op.drop_index(op.f('ix_recovery_cases_incident_provider'), table_name='recovery_cases')
    op.drop_index(op.f('ix_recovery_cases_id'), table_name='recovery_cases')
    op.drop_index(op.f('ix_recovery_cases_failure_reason'), table_name='recovery_cases')
    op.drop_index(op.f('ix_recovery_cases_execution_status'), table_name='recovery_cases')
    op.drop_index(op.f('ix_recovery_cases_customer_id'), table_name='recovery_cases')
    op.drop_index(op.f('ix_recovery_cases_classification'), table_name='recovery_cases')
    op.drop_index(op.f('ix_recovery_cases_checkout_id'), table_name='recovery_cases')
    op.drop_index(op.f('ix_recovery_cases_case_type'), table_name='recovery_cases')
    op.drop_index(op.f('ix_recovery_cases_case_id'), table_name='recovery_cases')
    op.drop_table('recovery_cases')
    op.drop_index(op.f('ix_recovery_budgets_merchant_id'), table_name='recovery_budgets')
    op.drop_index(op.f('ix_recovery_budgets_id'), table_name='recovery_budgets')
    op.drop_index(op.f('ix_recovery_budgets_budget_date'), table_name='recovery_budgets')
    op.drop_table('recovery_budgets')
    op.drop_index(op.f('ix_recovery_audit_logs_merchant_id'), table_name='recovery_audit_logs')
    op.drop_index(op.f('ix_recovery_audit_logs_id'), table_name='recovery_audit_logs')
    op.drop_index(op.f('ix_recovery_audit_logs_event_type'), table_name='recovery_audit_logs')
    op.drop_index(op.f('ix_recovery_audit_logs_created_at'), table_name='recovery_audit_logs')
    op.drop_index(op.f('ix_recovery_audit_logs_case_id'), table_name='recovery_audit_logs')
    op.drop_table('recovery_audit_logs')
    op.drop_index(op.f('ix_recovery_action_logs_status'), table_name='recovery_action_logs')
    op.drop_index(op.f('ix_recovery_action_logs_merchant_id'), table_name='recovery_action_logs')
    op.drop_index(op.f('ix_recovery_action_logs_id'), table_name='recovery_action_logs')
    op.drop_index(op.f('ix_recovery_action_logs_customer_id'), table_name='recovery_action_logs')
    op.drop_index(op.f('ix_recovery_action_logs_created_at'), table_name='recovery_action_logs')
    op.drop_index(op.f('ix_recovery_action_logs_case_id'), table_name='recovery_action_logs')
    op.drop_index(op.f('ix_recovery_action_logs_action'), table_name='recovery_action_logs')
    op.drop_table('recovery_action_logs')
    op.drop_index(op.f('ix_payment_events_status'), table_name='payment_events')
    op.drop_index(op.f('ix_payment_events_payment_id'), table_name='payment_events')
    op.drop_index(op.f('ix_payment_events_merchant_id'), table_name='payment_events')
    op.drop_index(op.f('ix_payment_events_id'), table_name='payment_events')
    op.drop_index(op.f('ix_payment_events_event_type'), table_name='payment_events')
    op.drop_index(op.f('ix_payment_events_event_id'), table_name='payment_events')
    op.drop_table('payment_events')
    op.drop_index(op.f('ix_circuit_breaker_states_provider'), table_name='circuit_breaker_states')
    op.drop_index(op.f('ix_circuit_breaker_states_id'), table_name='circuit_breaker_states')
    op.drop_table('circuit_breaker_states')
    op.drop_index(op.f('ix_checkout_sessions_status'), table_name='checkout_sessions')
    op.drop_index(op.f('ix_checkout_sessions_session_id'), table_name='checkout_sessions')
    op.drop_index(op.f('ix_checkout_sessions_merchant_id'), table_name='checkout_sessions')
    op.drop_index(op.f('ix_checkout_sessions_id'), table_name='checkout_sessions')
    op.drop_index(op.f('ix_checkout_sessions_customer_id'), table_name='checkout_sessions')
    op.drop_table('checkout_sessions')
    # ### end Alembic commands ###
