"""add_phase_7_postmortems

Revision ID: d9bb390e61c5
Revises: cd05eb882ec0
Create Date: 2026-08-30 12:12:56.945980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9bb390e61c5'
down_revision: Union[str, Sequence[str], None] = 'cd05eb882ec0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recovery_postmortems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('failure_stage', sa.String(), nullable=False),
    sa.Column('attempted_action', sa.String(), nullable=True),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('root_cause', sa.String(), nullable=True),
    sa.Column('ai_diagnosis', sa.String(), nullable=True),
    sa.Column('guardrail_result', sa.JSON(), nullable=True),
    sa.Column('execution_result', sa.JSON(), nullable=True),
    sa.Column('recovery_status', sa.String(), nullable=False),
    sa.Column('recovered_amount', sa.Integer(), nullable=False),
    sa.Column('recommended_followup', sa.String(), nullable=True),
    sa.Column('postmortem_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_postmortems_attempted_action'), 'recovery_postmortems', ['attempted_action'], unique=False)
    op.create_index(op.f('ix_recovery_postmortems_case_id'), 'recovery_postmortems', ['case_id'], unique=False)
    op.create_index(op.f('ix_recovery_postmortems_created_at'), 'recovery_postmortems', ['created_at'], unique=False)
    op.create_index(op.f('ix_recovery_postmortems_failure_stage'), 'recovery_postmortems', ['failure_stage'], unique=False)
    op.create_index(op.f('ix_recovery_postmortems_id'), 'recovery_postmortems', ['id'], unique=False)
    op.create_index(op.f('ix_recovery_postmortems_merchant_id'), 'recovery_postmortems', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_recovery_postmortems_recovery_status'), 'recovery_postmortems', ['recovery_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recovery_postmortems_recovery_status'), table_name='recovery_postmortems')
    op.drop_index(op.f('ix_recovery_postmortems_merchant_id'), table_name='recovery_postmortems')
    op.drop_index(op.f('ix_recovery_postmortems_id'), table_name='recovery_postmortems')
    op.drop_index(op.f('ix_recovery_postmortems_failure_stage'), table_name='recovery_postmortems')
    op.drop_index(op.f('ix_recovery_postmortems_created_at'), table_name='recovery_postmortems')
    op.drop_index(op.f('ix_recovery_postmortems_case_id'), table_name='recovery_postmortems')
    op.drop_index(op.f('ix_recovery_postmortems_attempted_action'), table_name='recovery_postmortems')
    op.drop_table('recovery_postmortems')
    # ### end Alembic commands ###
