"""add recovery action latency

Revision ID: bed9ff52b9a5
Revises: d9bb390e61c5
Create Date: 2026-08-31 08:49:39.733275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bed9ff52b9a5'
down_revision: Union[str, Sequence[str], None] = 'd9bb390e61c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recovery_action_logs', sa.Column('latency_seconds', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recovery_action_logs', 'latency_seconds')
    # ### end Alembic commands ###
