"""add_phase_7_audit_trail

Revision ID: cd05eb882ec0
Revises: 509de1c0945a
Create Date: 2026-08-30 11:32:50.070512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd05eb882ec0'
down_revision: Union[str, Sequence[str], None] = '509de1c0945a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recovery_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('event_source', sa.String(), nullable=False),
    sa.Column('decision', sa.String(), nullable=True),
    sa.Column('reasoning', sa.String(), nullable=True),
    sa.Column('guardrail_result', sa.JSON(), nullable=True),
    sa.Column('execution_result', sa.JSON(), nullable=True),
    sa.Column('audit_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_audit_logs_case_id'), 'recovery_audit_logs', ['case_id'], unique=False)
    op.create_index(op.f('ix_recovery_audit_logs_created_at'), 'recovery_audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_recovery_audit_logs_event_type'), 'recovery_audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_recovery_audit_logs_id'), 'recovery_audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_recovery_audit_logs_merchant_id'), 'recovery_audit_logs', ['merchant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recovery_audit_logs_merchant_id'), table_name='recovery_audit_logs')
    op.drop_index(op.f('ix_recovery_audit_logs_id'), table_name='recovery_audit_logs')
    op.drop_index(op.f('ix_recovery_audit_logs_event_type'), table_name='recovery_audit_logs')
    op.drop_index(op.f('ix_recovery_audit_logs_created_at'), table_name='recovery_audit_logs')
    op.drop_index(op.f('ix_recovery_audit_logs_case_id'), table_name='recovery_audit_logs')
    op.drop_table('recovery_audit_logs')
    # ### end Alembic commands ###
